### ISSUE TITLE
is `clearStore` implemented?

### ISSUE THREAD

**Issue by idkjs** [reasonml-community/reason-apollo-client#30]
I see it greyed out. Is it accessible as a renamed method?

Thank you for the awesome work here!

**Comment by idkjs** [comment]
Disregard. Thanks.

**Comment by jeddeloh** [comment]
It is not, but just put up a PR for it: #31

**Comment by idkjs** [comment]
nice.

Is this right? Let me check my work.

I just stuck this in the file I needed it in:

```reason
[@bs.module "@apollo/client"]
external clearStore: unit => Js.Promise.t(unit) = "clearStore";
```

I guess I should have checked the api!

Be sure to stick an example in the example.

Thanks for sharing!

**Comment by jeddeloh** [comment]
I think it's a method on the client, so you need to use `@bs.send`: https://github.com/reasonml-community/reason-apollo-client/pull/31/files#diff-29c69931ac1ef85558a4d78ff081ea16R310

**Comment by jeddeloh** [comment]
I just merged. You can try it out by installing `reason-apollo-client@dev` before the next release if you like
