### ISSUE TITLE
Using custom ws implementation

### ISSUE THREAD

**Issue by mattdamon108** [reasonml-community/reason-apollo-client#33]
Hi,

Actually, I'm trying to use this module on the ground of Gatsby. I faced the one problem which is the error in process of building the static page. I guess the `ws` is not existing in node env during building Gatsby static page.

![image](https://user-images.githubusercontent.com/36963424/91109632-8b13fa00-e6b6-11ea-837d-7caeb7e2b55f.png)

So, I tried to add `~webSocketImpl`, but no gain.

Can you give me a tip to use a custom ws implementation? using JS module`ws` or `bs-ws` which is binding to `ws`.

> reference
https://github.com/apollographql/subscriptions-transport-ws/issues/191

**Comment by jeddeloh** [comment]
Can you give me a little more detail of what you mean by "no gain"? I would expect something like this to work:
```
[@bs.module "ws"]
external ws: ApolloClient.Link.WebSocketLink.webSocketImpl = "default";

let wsLink =
  ApolloClient.Link.WebSocketLink.make(~uri="wss://yourendpoint.com", ~webSocketImpl=ws, ());
```
Are you getting a type error or what exactly is the error you're encountering?

I haven't looked at `bs-ws`, but if you want to use that, it will not have the same types. You'll need to cast it to `ApolloClient.Link.WebSocketLink.webSocketImpl` using `%identity` or `Obj.magic` and then pass it in.

**Comment by mattdamon108** [comment]
@jeddeloh  Thank you very much, it fixes my problem. Frankly, I'm very new to ReasonML, so I'm not much experienced with `@bs` decorator yet. Thank you again.

```reason
[@bs.module "ws"]
external ws: ApolloClient.Link.WebSocketLink.webSocketImpl = "default";

let wsLink =
  ApolloClient.Link.WebSocketLink.(
    make(
      ~uri="ws://" ++ graphqlEndpoint,
      ~options=
        ClientOptions.make(
          ~connectionParams=ConnectionParams(Obj.magic(headers)),
          ~reconnect=true,
          (),
        ),
      ~webSocketImpl=ws,
      (),
    )
  );
```

**Comment by jeddeloh** [comment]
No problem. Welcome to Reason!
