### ISSUE TITLE
Calling Delete Mutation

### ISSUE THREAD

**Issue by idkjs** [reasonml-community/reason-apollo-client#38]
I am messing with the demo and created this file from the `Mutation.re` example:

```ocaml
module Cache = ApolloClient.Cache;

module DeleteTodoMutation = [%graphql
  {|
    mutation DeleteTodo ($id:String!){
      deleteTodoItem(input: { id: $id }) {
        deletedTodoItemId
        clientMutationId
      }
    }
  |}
];

```

When I call this as is it compiles and fails. To make it work, it has to be

```ocaml
module Cache = ApolloClient.Cache;

module DeleteTodoMutation = [%graphql
  {|
    mutation DeleteTodo ($id:ID!){
      deleteTodoItem(input: { id: $id }) {
        deletedTodoItemId
        clientMutationId
      }
    }
  |}
];

```

Is this expected? Figured the typing was supposed to catch that. Working example is in #37

**Comment by jeddeloh** [comment]
I think this is an issue for `graphql-ppx`. Before you poste there, though, I noticed you're using `graphql-ppx-beta.11` which is quite a bit out of date. You might want to verify the behavior on `beta.22` first.

**Comment by idkjs** [comment]
You want me to update the deps on your example?

**Comment by jeddeloh** [comment]
I think we're good now.
