### ISSUE TITLE
Use Js.Nullable.t

### ISSUE THREAD

**Issue by celsobonutti** [reasonml-community/reason-apollo-client#59]
This is more a question than an issue per se (sorry, I didn't know where to ask this), but is it possible to use `Js.Nullable.t` with `ApolloClient.query`?
I'm asking this because I'm using it with Next.js and wanted to do some SSR. Since getServerSideProps converts the props to JSON before sending them to React, I'm getting errors:
```
SerializableError: Error serializing `.projects._0[0].description` returned from `getServerSideProps` in "/projects".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value all together.
```
Converting all of the `option`als to `Js.Nullable.t` worked but, since they are generated as Nullables by graphql-ppx, I would like to know if there's any way to access them in this library.

Thank you very much!

**Comment by jfrolich** [comment]
Do you mean the result of the query. If there is a way to not `parse` the result by `graphql-ppx` then you get the original JSON compatible result that isn't parsed yet into Reason types (and thus has undefined values for optionals). You can then parse the result manually. @jeddeloh, having a hook to get the unparsed result would be quite nice indeed for these kinds of use-cases.

**Comment by jfrolich** [comment]
I just realized, you can also use `Query.serialize` to serialize it to JSON compatible from the query result. That would work right now.

**Comment by jeddeloh** [comment]
Yeah, it's not 100% clear to me what is being asked here, but I think you would want to do exactly as @jfrolich says. `Query.serialize` the data before going into the component and then `Query.parse` inside the component. I'm not that familiar with Next.js, though. @celsobonutti please let us know if we're off here.

Since you kinda have to know how to manually do the thing inside the component, maybe it's fine to just recommend the manual `serialize` as well rather than adding an unparsed api surface. Thoughts?

**Comment by celsobonutti** [comment]
That's exactly what I needed, I think I missed this part in the `graphql-ppx` docs (just saw it there, now). Thank you very much @jfrolich and @jeddeloh! 

I do agree it's better to use the manual serialize, don't think there's a need for making a new API for so rare (and easily solvable) use cases, which could also create some confusion on which hook to use.

I'll leave this issue open in case you want to keep this discussion, anyway.

By the way, thank you a lot for all of your work, this library is awesome!
