### ISSUE TITLE
Why records instead of Variants?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reasonml-community/reason-apollo-client#76]
Hi,

Any reason why the `use` function returns records instead of variants?

**Comment by jeddeloh** [comment]
Some of us found them to be a bit of a trap. You can see the discussion in the original reason-apollo-hooks PR here: https://github.com/reasonml-community/reason-apollo-hooks/pull/122#issuecomment-633560391

**Comment by jfrolich** [comment]
Mostly because the state was not always mutually exclusive - like it can be (re)loading and have data - so you would end up with a lot of variants. A product type is better for this, and we can pattern match on it as well.
