### ISSUE TITLE
Mutation example

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reasonml-community/reason-apollo-client#77]
https://github.com/reasonml-community/reason-apollo-client/blob/master/EXAMPLES/src/hooksUsage/Mutation.re#L41

For the first time user this example might be hard to understand. something like `mutate(varaiblerecords) |> Js.Promise.then()` might be simple. If it is fine I can send a PR.

**Comment by jeddeloh** [comment]
Agreed. As-is, though, it's just meant to be a reference to enumerate use of (and exercise) the api surface. I'm going to switch the repo to rescript here shortly and then do a quick pass at the documentation site where this won't be as much of an issue. So maybe hold off for that, but afterward, contribution to better documentation site and refinement of examples is appreciated
